name: Build and Test Java Project

on:
    pull_request:
       types: [opened, edited, synchronized]
    workflow_dispatch:
 

jobs:
  task-check:
    runs-on: [self-hosted, ADC]
    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"  
  build_and_test:
    runs-on: [self-hosted, ADC]
            
    steps:
    - uses: actions/checkout@v4
      with: 
        path: ${{ github.sha }}

    - name: Set up JDK 18
      uses: actions/setup-java@v1
      with:
        java-version: 18

    - name: Build and test project with Maven
      run: mvn clean install
