name: Review Comment

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'master'
      - 'rel/**'
      - '!sbd/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  post-comment:
    runs-on: [self-hosted, Linux-ADC]

    steps:
      - name: Post Checklist Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            - Please perform a thorough self-review of your pull request before submitting it for further review. Once completed, enter the comment: /self-reviewed
