name: Automated Ollama Code Review

on:
  workflow_dispatch:
    
jobs:
  task-check:
    runs-on: [self-hosted, ADC]
    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
  ollama_review:
    runs-on: self-hosted
    name: Ollama Code Review
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get modified files
        id: get-modified-files
        uses: tj-actions/changed-files@v43

      - name: Review modified files
        env:
          GITHUB_ENTERPRISE_TOKEN: ${{ github.token }}
          GH_HOST: "github.deutsche-boerse.de"
        run: |
          for file in ${{ steps.get-modified-files.outputs.all_changed_files }}; do
            review_prompt="Review the following file:\n\n\`\`\`\n$(cat $file)\n\`\`\`"
            echo $review_prompt
            modified_file_review=$(curl -s http://10.127.16.231:11434/api/generate -d '{"model": "codeqwen", "prompt": $review_prompt, "stream": false}' | jq -r '.response')
            file_comment="Ollama Code Review for \`$file\`:\n\n$modified_file_review"
            echo "$file_comment" >> ollama_review.txt
          done
          gh pr comment ${{ github.event.pull_request.number }} --body "$(cat ollama_review.txt)"
        shell: bash
