name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  check-tag:
    runs-on: [self-hosted, ADC]
    permissions: write-all
    steps:
      - uses: "actions/checkout@v4"
        with:
          path: ${{ github.sha }}

 
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5.0.0
        with:
          baseUrl: https://github.deutsche-boerse.de/api/v3
          fromTag: ${{ github.base_ref }}
          toTag: ${{ github.head_ref }}
          mode: "COMMIT"
      
      - name: Store Changelog
      # Put output through env variable to make it robust to quotes
        env:
           CHANGELOG: ${{steps.build_changelog.outputs.changelog}}
        run: |
             echo "$CHANGELOG" >> $GITHUB_STEP_SUMMARY

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: false
          prerelease: false
          
      - name: Upload Release Notes
        uses: softprops/action-gh-release@v2.0.8
        with:
           body: ${{ steps.build_changelog.outputs.changelog }}
    


              
      

          
