name: Branch Synchronization
on:
  schedule:
    - cron: '0 3 * * MON' # run every Monday at 3am
  workflow_dispatch: # enables manual triggering

jobs:
  sync-branches:
    runs-on: [self-hosted, Linux-ADC]
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "master"
          TO_BRANCH: "sync"
